### ISSUE TITLE
[CHECKLIST] Liquid staking

### ISSUE THREAD

**Issue by 1xstj** [tangle-network/tangle-restaking-parachain#2]
Tasks

### LST pallet

- [x] Integrate assets pallet 
- [x] Create LST pallet and issue wrapped liquid tokens
- [x] Create xcm adapter pallet that will issue wrapped liquid tokens from xcm calls

### XCM 

- [x] Setup a local xcm test and integrate parachain local networks (moonbeam/astar/bifrost)
- [x] setup xtokens test for wrapped assets

### Oracle

- [x] Setup an oracle pallet to price all LST assets
- [x] Setup oracle trait for LST pallet to read data 

https://forum.polkadot.network/t/slpx-the-omni-chain-liquid-staking-vision-via-xcm/3836
https://docs.bifrost.finance/builders/liquid-staking-slp/vdot
